# Operator with there Precedence.
all_operators = {
    "+": 1,
    "-": 1,
    "*": 2,
    "/": 2,
    "%": 2,
    "^": 2,
    "abs": 3,
    "gcd": 3,
    "ceil": 3,
    "fact": 3,
    "floor": 3,
    "exp": 3,
    "pow": 3,
    "sqrt": 3,
    "log": 3,
    "ln": 3,
    "log2": 3,
    "sin": 3,
    "cos": 3,
    "tan": 3,
    "asin": 3,
    "acos": 3,
    "atan": 3,
    "sinh": 3,
    "cosh": 3,
    "tanh": 3,
    "asinh": 3,
    "acosh": 3,
    "atanh": 3,
    "hypot": 3,
    "deg": 3,
    "rad": 3,
    "(": 1,
    ")": 1
}